### ISSUE TITLE
Switch 3560 password

### ISSUE THREAD

**Issue by danishx007** [sekti92/it_infrastructure#1]
Hii. Can you please share the password of the Multi layer switch Secret password?(3560 Building pc)
![Capture](https://user-images.githubusercontent.com/65561424/86532218-967e4c80-bee1-11ea-9a3f-61b6088c5865.PNG)

**Comment by sekti92** [comment]
HI there unfortunately i don't remember the password, it's a long time ago

**Comment by danishx007** [comment]
Well thankyou (:
